name: PHP

on:
  - push
  - schedule: [cron: '0 0 * * 0']

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    # TODO strategy:
      # TODO matrix: {php: ['7.2', '7.3']}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: |
          composer global require cedx/coveralls
          composer install --no-interaction
      - name: Test
        run: composer run-script test
      - name: Coverage
        if: success()
        run: composer run-script coverage
